user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
}

stream {

    upstream user_db {
        server pg-user:5432;
    }

    upstream book_db {
        server pg-book:5432;
    }

    upstream activity_db {
        server pg-activity:5432;
    }

    upstream redis_db {
        server redis:6379;
    }

    upstream mongo_db {
        server mongodb:27017;
    }

    server {
        listen 15432;
        proxy_pass user_db;
        proxy_timeout 10m;
        proxy_connect_timeout 30s;
    }

    server {
        listen 15433;
        proxy_pass book_db;
        proxy_timeout 10m;
        proxy_connect_timeout 30s;
    }

    server {
        listen 15434;
        proxy_pass activity_db;
        proxy_timeout 10m;
        proxy_connect_timeout 30s;
    }

    server {
        listen 16379;
        proxy_pass redis_db;
    }

    server {
        listen 17017;
        proxy_pass mongo_db;
    }
}